language: julia
notifications:
  email: false
julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly
script:
  - |
      julia -e '
          VERSION >= v"0.7.0-DEV.3656" && using Pkg
          VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("Decimals"))
          Pkg.add("Coverage")
          using Coverage
          Coveralls.submit(Coveralls.process_folder())
      '
